module.exports = {
  apps: [
    {
      name: 'alphxc-cspr-trade-mcp',
      script: 'node_modules/.bin/cspr-trade-mcp',
      cwd: '/root/alphx/cspr-trade-mcp',
      env: {
        CSPR_TRADE_NETWORK: 'testnet',
        CSPR_TRADE_TRANSPORT: 'http',
        CSPR_TRADE_PORT: '3001',
      },
    },
    {
      name: 'alphxc-api',
      script: 'python3',
      args: '-m uvicorn backend.main:app --host 0.0.0.0 --port 8400',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-yahoo',
      script: 'backend/agents/yahoo_agent.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-twelvedata',
      script: 'backend/agents/twelvedata_agent.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-aggregator',
      script: 'backend/agents/aggregator_agent.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-trader-a',
      script: 'backend/agents/trader_a.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-trader-b',
      script: 'backend/agents/trader_b.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-trader-c',
      script: 'backend/agents/trader_c.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
    {
      name: 'alphxc-settler',
      script: 'backend/agents/settler_agent.py',
      interpreter: 'python3',
      cwd: '/root/alphx',
      env: { PYTHONPATH: '/root/alphx' },
    },
  ],
}
